name: Deploy FrontEnd

on:
  push:
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Extract latest version + short SHA
        id: versioning
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 || echo "v1.0.0")
          VERSION_NUMBER=${LATEST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_NUMBER"
          NEW_VERSION="v$MAJOR.$MINOR.$((PATCH + 1))"

          SHORT_SHA=$(git rev-parse --short HEAD)
          IMAGE_TAG="${NEW_VERSION#v}-${SHORT_SHA}"

          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}"/task-app-front:${IMAGE_TAG} .
          docker push "${{ secrets.DOCKER_USERNAME }}"/task-app-front:${IMAGE_TAG}
      
      - name: Push new Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "${{ env.NEW_VERSION }}"
          git push origin "${{ env.NEW_VERSION }}"
